#!/usr/bin/env python3
"""Generates the club's own poster art as 11x17 sheets with the QR strip.

The members made these as images (club/NN-name.webp|jpg|png). Each sheet is
the image, full width and fitted whole into 1056 x 1408 (object-fit: contain;
a blurred copy fills any side bands, so no lettering is ever cropped), over a 224 px paper strip carrying the
club mark and the two QR codes. The art itself is never painted over.

    python3 gen_club.py && python3 build.py

A poster whose art is missing is skipped (and its old sheet removed). After
adding art, also add the sheet to assets/posters.js so the site lists it.
"""
import glob, os

HERE = os.path.dirname(os.path.abspath(__file__))
# (sheet name, image stem in club/, title, object-position)
POSTERS = [
    ('20-club-own-the-skies',   '01-own-the-skies',          'Own the Skies',          '50% 50%'),
    ('21-club-learn-to-fly',    '02-learn-to-fly-formation', 'Learn to Fly (formation)', '50% 40%'),
    ('22-club-command-storm',   '03-command-the-storm',      'Command the Storm',      '50% 50%'),
    ('23-club-learn-to-fly-2',  '04-learn-to-fly-sunset',    'Learn to Fly (sunset)',  '50% 50%'),
    ('24-club-tba',             '05-tba',                    'TBA',                    '50% 50%'),
    ('25-club-dream-big',       '06-dream-big',              'Dream Big, Fly Far',     '50% 50%'),
]

LOGO = '''<svg viewBox="0 0 64 64" fill="none" stroke-width="2.4" aria-hidden="true"><circle cx="32" cy="32" r="29" stroke="#2b4d9c"/><circle cx="32" cy="32" r="19" stroke="#b9348a"/><path d="M8 34 L30 30 L32 22 L34 30 L56 34 L34 35 L33 44 L38 47 L26 47 L31 44 L30 35 Z" stroke="#1c1c1c" fill="#ffffff" stroke-linejoin="round"/></svg>'''

TPL = '''<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{title} - Brophy Aviators</title>
<link rel="stylesheet" href="poster.css">
<!-- GENERATED by gen_club.py - edit that, not this. -->
<style>
  .art{{position:absolute;left:0;top:0;width:1056px;height:1408px;overflow:hidden;background:#0c0d10}}
  .art img{{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;display:block}}
  .art img.fill{{object-fit:cover;filter:blur(28px) brightness(.8);transform:scale(1.15)}}
  .strip{{position:absolute;left:0;right:0;bottom:0;height:224px;border-top:3px solid var(--blue);
    display:flex;align-items:center;justify-content:space-between;padding:0 40px;overflow:hidden;background-color:var(--paper)}}
  .strip .chartbg{{opacity:.55}}
  .strip > :not(.chartbg){{position:relative;z-index:1}}
  .strip > div:nth-child(2){{flex:1;min-width:0}}
  .mast svg{{width:66px;height:66px}}
  .mast .club{{font-size:27px}}
  .mast .sub{{font-size:14px;letter-spacing:.22em}}
  .tag{{font-size:19px;color:var(--muted);margin-top:16px;max-width:400px;line-height:1.3}}
  .qrs{{gap:14px}}
  .qr{{padding:12px 14px 12px 12px;gap:12px}}
  .qr img{{width:144px;height:144px}}
  .qr .say{{font-size:15px;max-width:118px}}
  .qr .say b{{font-size:19px;margin-bottom:6px}}
</style></head>
<body>
<div class="art">{art}</div>
<div class="strip">
  <div class="chartbg" id="chart"></div>
  <div>
    <div class="mast">{logo}<div><div class="club">Brophy Aviators Club</div><div class="sub">Flight simulator lab</div></div></div>
    <div class="tag">Flight Simulator 2024 &middot; yoke &amp; pedals &middot; VR on a motion rig</div>
  </div>
  <div class="qrs">
    <div class="card magenta qr"><img src="qr-join.svg" alt=""><div class="say"><b>Join</b>The club sign-up form</div></div>
    <div class="card teal qr"><img src="qr-site.svg" alt=""><div class="say"><b>Hours</b>Live leaderboard &amp; lab hours</div></div>
  </div>
</div>
<script src="chart.js"></script>
<script>drawChart(document.getElementById('chart'), {{ alpha: .8 }});</script>
</body></html>
'''

for name, stem, title, pos in POSTERS:
    found = sorted(glob.glob(os.path.join(HERE, 'club', stem + '.*')))
    if found:
        src = 'club/' + os.path.basename(found[0])
        art = '<img class="fill" src="%s" alt=""><img src="%s" alt="">' % (src, src)
    else:
        # No sheet until the art exists, so build.py never prints a placeholder.
        stale = os.path.join(HERE, name + '.html')
        if os.path.exists(stale): os.remove(stale)
        print(name, 'SKIPPED - save the art as posters/src/club/%s.jpg (or .png/.webp)' % stem)
        continue
    with open(os.path.join(HERE, name + '.html'), 'w') as f:
        f.write(TPL.format(title=title, pos=pos, art=art, logo=LOGO))
    print(name, 'ok')
